const cartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CHECKOUT : 'CLEAR_ITEM_FROM_CHECKOUT',
    REMOVE_ITEM : 'REMOVE_ITEM' ,
    CLEAR_CART : 'CLEAR_CART'
}

export default cartActionTypes